### ISSUE TITLE
Generating CIFAR-FS dataset

### ISSUE THREAD

**Issue by eugenelet** [hushell/sib_meta_learn#1]
Hi there, nice work on achieving the SoTA of few-shot learning. Here's a small issue that I encountered when I tried to run the code for CIFAR-FS. I think that `download_cifarfs.sh` doesn't generate the necessary files required for CIFAR-FS dataset. Can you confirm on this part? Thanks a lot!

**Comment by XiSHEN0220** [comment]
Hi, thank you for your interest in the project!

For your question, I did a fresh pull from the Master branch and was able to download the dataset. 
Maybe you can try again with: 

cd data 
bash download_cifarfs.sh

**Comment by XiSHEN0220** [comment]
Also, check whether you can use Dropbox.

**Comment by eugenelet** [comment]
Hi, I've down the download of CIFAR-FS using `bash download_cifarfs.sh` and tried training the feature network using: `python3 main_feat.py --outDir CIFAR_WRN_60Epoch --cuda --dataset Cifar --nbEpoch 60`
I got
`FileNotFoundError: [Errno 2] No such file or directory: './data/cifar-fs/train/'`
as the error message. I assume the there's an error in the handling of file in `download_cifarfs.sh`?

Edit: I've found the problem. The reason is because that `python3` is used instead of `python2` which is soft-linked by `python` in my environment. Thanks for looking into my issue. Problem solved :)

**Comment by hushell** [comment]
Hi @eugenelet 
Thank you for your interests! The CIFAR-FS dataset pieces are on Dropbox as well as downloading through the python script ```./data/get_cifards.py```
Try to see if you can access to 
```
https://www.dropbox.com/s/wuxb1wlahado3nq/cifar-fs-splits.zip?dl=0
https://www.dropbox.com/s/g9ru5ac5tpupvg6/netFeatBest62.561.pth?dl=0
```

**Comment by eugenelet** [comment]
Hi @hushell , thanks for your reply, I've fixed the problem where the solution is mentioned in my previous comment. Thanks for going through my issue for such a trivial mistake. Nice work here and thanks for your contribution on meta-learning :)
