### ISSUE TITLE
How to train without loading pretraining model

### ISSUE THREAD

**Issue by w-tingting** [hushell/sib_meta_learn#3]

**Comment by hushell** [comment]
The feature extractor is actually executed in the `torch.no_grad` context, so if you don't load the pretrained feature extractor, you'll need to remove the `torch.no_grad` thing. This way of training every module end-to-end is in theory doable, although we didn't try that in our experiments.

**Comment by w-tingting** [comment]
thank you for your reply！ 发自 网易邮箱大师 ---- 回复的原邮件 ---- 发件人 Shell ***@***.***> 日期 2021年10月07日 18:14 收件人 ***@***.***> 抄送至 ***@***.***>、State ***@***.***> 主题 Re: [hushell/sib_meta_learn] How to train without loading pretraining model (#3) The feature extractor is actually executed in the torch.no_grad context, so if you don't load the pretrained feature extractor, you'll need to remove the torch.no_grad thing. This way of training every module end-to-end is in theory doable, although we didn't try that in our experiments. — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
